sqlite3: &sqlite3
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql2: &mysql2
  adapter: mysql2
  username: travis
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  database: counter_culture_test
  <<: *<%= ENV['DB'] || 'sqlite3' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
