language: ruby
rvm:
  - "2.3.8"
  - "2.4.6"
  - "2.5.5"
  - "2.6.2"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
env:
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install:
  - bundle update
script: TRAVIS=true bundle exec rake spec
